apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api-deployment
  labels:
    app: ticket-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
      - name: ticket-api
        image: parvir/ticket-api:latest
        imagePullPolicy: "Always"
        env:
        - name: AWS_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username   
        - name: AWS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        - name: AWS_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: credentials
              key: rdsEndpoint        
        ports:
        - containerPort: 8081
