all:
  children:
    jenkins:
      hosts:
        34.255.200.231:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "~/hold/qa-amazon.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
