- hosts: 34.244.75.26
  become: true
  tasks:
  - name: "Transfer script"
    copy: "src=~/ansible/install_jenkins.sh dest=/home/ubuntu/"
  - name: "Make script executable"
    command: "chmod +x /home/ubuntu/install_jenkins.sh"  
  - name: "Install Jenkins"
    command: "sh /home/ubuntu/install_jenkins.sh"
  - name: "Transfer docker script"
    copy: "src=~/ansible/install_docker.sh dest=/home/ubuntu/"
  - name: "Make the docker script executable"
    command: "chmod +x /home/ubuntu/install_docker.sh"
  - name: "Install Docker"
    command: "sh /home/ubuntu/install_docker.sh"
  - name: "Transfer AWS install script"
    copy: "src=~/ansible/install_aws_cli.sh dest=/home/ubuntu"
  - name: "Make script executable"
    command: "chmod +x /home/ubuntu/install_aws_cli.sh"
  - name: "Install AWS cli"
    command: "sh /home/ubuntu/install_aws_cli.sh"
  - name: "Transfer kubernetes script"
    copy: "src=~/ansible/install_kubernetes.sh dest=/home/ubuntu/"
  - name: "Make script executable"
    command: "chmod +x /home/ubuntu/install_kubernetes.sh"
  - name: "Install Kubernetes CLI"
    command: "sh /home/ubuntu/install_kubernetes.sh"   
